server:
  port: 45556

withdrawal-events-topic: 'withdrawal-events-topic'
deposit-events-topic: 'deposit-events-topic'

logging.level:
  org.springframework.orm.jpa.JpaTransactionManager: TRACE
  org.apache.kafka.clients.producer.internals.TransactionManager: DEBUG
  org.hibernate.SQL: DEBUG


spring:
  kafka:
    producer:
      bootstrap-servers: 'localhost:9092'
      key-serializer: 'org.apache.kafka.common.serialization.StringSerializer'
      value-serializer: 'org.springframework.kafka.support.serializer.JacksonJsonSerializer'
      acks: 'all'
      transactional-id-prefix: 'transfer-microservice-'
      properties:
        spring.json.trusted.packages: 'org.appsdeveloperblog.core.events'
        delivery.timeout.ms: '120000'
        linger.ms: '0'
        request.timeout.ms: '30000'
        max.in.flight.requests.per.connection: '5'
        enable.idempotence: 'true'

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

