server:
  port: '0'

withdrawal-events-topic: 'withdrawal-events-topic'
deposit-events-topic: 'deposit-events-topic'

logging.level:
  org.springframework.kafka.transaction: 'TRACE'
  org.springframework.transaction: 'TRACE'
  org.apache.kafka.clients.producer.internals.TransactionManager: 'TRACE'

spring:
  kafka:
    producer:
      bootstrap-servers: 'localhost:9092'
      key-serializer: 'org.apache.kafka.common.serialization.StringSerializer'
      value-serializer: 'org.springframework.kafka.support.serializer.JacksonJsonSerializer'
      acks: 'all'
      transactional-id-prefix: 'transfer-microservice-'
      properties:
        spring.json.trusted.packages: 'org.appsdeveloperblog.core.events'
        delivery.timeout.ms: '120000'
        linger.ms: '0'
        request.timeout.ms: '30000'
        max.in.flight.requests.per.connection: '5'
        enable.idempotence: 'true'